/* Stable curriculum IDs are shared by notebooks, lessons, exercises and AI. */
(function (root) {
  "use strict";
  const subjects = [
    { id: "math", name: "数学", available: true },
    { id: "physics", name: "物理", available: true },
    { id: "chemistry", name: "化学", available: true },
    { id: "biology", name: "生物", available: true },
  ];
  const topicSubjects = {
    sets: "math",
    quad: "math",
    equation: "math",
    property: "math",
    circle: "math",
    linecircle: "math",
    cube: "math",
    distance: "physics",
    motion: "physics",
    force: "physics",
  };
  /* 分类树：按学科领域分组，用于知识图谱导航（与先修 DAG 并存）。 */
  const categories = {
    math: [
      { id: "logic",     name: "常用逻辑用语", icon: "\u2234" },
      { id: "sets-cat",  name: "集合",         icon: "\u2229" },
      { id: "ineq",      name: "不等式",       icon: "\u2276" },
      { id: "func",      name: "函数",         icon: "\u223F" },
      { id: "eq",        name: "方程",         icon: "\u224D" },
      { id: "geo-circle",name: "几何\u00B7圆",  icon: "\u2299" },
      { id: "geo-solid", name: "几何\u00B7立体", icon: "\u25FB" },
    ],
    physics: [
      { id: "kinematics", name: "运动学基础", icon: "\u21D2" },
      { id: "mechanics",  name: "力学",       icon: "\u2192" },
    ],
    chemistry: [{ id: "chem-base", name: "化学基础", icon: "\u2697" }],
    biology:   [{ id: "bio-base",  name: "生物基础", icon: "\u{1F9EC}" }],
  };
  /* 节点 → 分类的映射（每个节点只属于一个分类，形成严格树）。 */
  const nodeCategory = {
    proposition: "logic", quantifier: "logic",
    sets: "sets-cat",
    sign: "ineq", "ineq-basic": "ineq", quadratic: "ineq", roots: "ineq", "param-quad": "ineq",
    quad: "func", property: "func",
    equation: "eq",
    circle: "geo-circle", linecircle: "geo-circle",
    cube: "geo-solid",
    distance: "kinematics", motion: "kinematics", time: "kinematics", rate: "kinematics", algebra: "kinematics", midterm: "kinematics", unequal: "kinematics", "eq-interval": "kinematics", "formula-select": "kinematics",
    force: "mechanics",
    balance: "chem-base",
    inheritance: "bio-base",
  };
  const nodes = [
    [
      "proposition",
      "math",
      "命题与常用逻辑用语",
      "四种命题转换、命题的否定与否命题、充分必要条件",
      [],
      null,
      "proposition",
      "logic",
    ],
    [
      "quantifier",
      "math",
      "全称量词与存在量词",
      "量词命题的否定、全称与存在的互换、量词与参数范围",
      ["proposition"],
      null,
      "quantifier",
      "logic",
    ],
    [
      "sets",
      "math",
      "集合与集合运算",
      "交集、并集、补集及元素归属",
      ["proposition"],
      "sets",
      null,
      "sets-cat",
    ],
    [
      "ineq-basic",
      "math",
      "不等式性质与作差法",
      "不等式基本性质、作差法比较大小、范围运算与常见陷阱",
      [],
      null,
      "ineq-basic",
      "ineq",
    ],
    [
      "quad",
      "math",
      "二次函数的参数",
      "开口、顶点、对称轴与退化情况",
      [],
      "quad",
      null,
      "func",
    ],
    [
      "param-quad",
      "math",
      "含参一元二次不等式",
      "参数分类讨论、判别式法、二次项系数含参的临界处理",
      ["ineq-basic", "quad"],
      null,
      "param-quad",
      "ineq",
    ],
    [
      "equation",
      "math",
      "方程与不等式",
      "方程根与函数图像、解集和端点",
      ["quad", "param-quad"],
      "equation",
      null,
      "eq",
    ],
    [
      "property",
      "math",
      "单调性与奇偶性",
      "定义域、增减、奇偶与对称",
      [],
      "property",
      null,
      "func",
    ],
    [
      "circle",
      "math",
      "圆与圆周角",
      "圆心角、同弧圆周角与直径特例",
      [],
      "circle",
      null,
      "geo-circle",
    ],
    [
      "linecircle",
      "math",
      "直线与圆的位置关系",
      "圆心距、相交相切相离与弦长",
      ["equation"],
      "linecircle",
      null,
      "geo-circle",
    ],
    [
      "cube",
      "math",
      "正方体与线面角",
      "体对角线、投影与线面所成角",
      [],
      "cube",
      null,
      "geo-solid",
    ],
    [
      "distance",
      "physics",
      "路程与位移",
      "标量与矢量、方向、往返运动",
      [],
      "distance",
      null,
      "kinematics",
    ],
    [
      "motion",
      "physics",
      "匀变速直线运动",
      "恒加速度条件、速度时间图与位移",
      ["distance"],
      "motion",
      null,
      "kinematics",
    ],
    [
      "force",
      "physics",
      "力、质量与加速度",
      "合力、质量与牛顿第二定律",
      ["motion"],
      "force",
      null,
      "mechanics",
    ],
    [
      "time",
      "physics",
      "时刻、时间段与中点",
      "第 n 秒内、秒末、两段时间各自中点",
      [],
      null,
      "time",
      "kinematics",
    ],
    [
      "rate",
      "physics",
      "平均量、比值与单位",
      "总位移除以总时间、加权平均",
      ["distance"],
      null,
      "rate",
      "kinematics",
    ],
    [
      "algebra",
      "physics",
      "倍数、变化量与列式",
      "末速度与速度变化量、倍数和消元",
      ["rate"],
      null,
      "algebra",
      "kinematics",
    ],
    [
      "midtime",
      "physics",
      "平均速度对应哪个时刻",
      "匀变速条件、中时速与中位速",
      ["time", "rate", "motion"],
      null,
      "midtime",
      "kinematics",
    ],
    [
      "unequal",
      "physics",
      "等距离、不等时间",
      "两段平均速度对应中点、速度差除以中点时间差",
      ["time", "midtime"],
      null,
      "unequal",
      "kinematics",
    ],
    [
      "eq-interval",
      "physics",
      "等时位移差与比例推论",
      "Δs=aT²、逐差法、初速度为零的 1:3:5 比例结论",
      ["time", "motion"],
      null,
      "eq-interval",
      "kinematics",
    ],
    [
      "formula-select",
      "physics",
      "匀变速四公式的推导与选用",
      "两基本公式消元推导其余、按缺项选公式、刹车停止陷阱",
      ["motion", "algebra"],
      null,
      "formula-select",
      "kinematics",
    ],
    [
      "sign",
      "math",
      "负数、数轴与不等号",
      "乘除负数变号、乘零信息丢失",
      [],
      null,
      "sign",
      "ineq",
    ],
    [
      "quadratic",
      "math",
      "二次不等式与参数分类",
      "系数正负零、端点与因式分解",
      ["sign", "quad"],
      null,
      "quadratic",
      "ineq",
    ],
    [
      "roots",
      "math",
      "穿根法与重根",
      "奇根变号、偶根不变号、孤立零点",
      ["quadratic"],
      null,
      "roots",
      "ineq",
    ],
    [
      "balance",
      "chemistry",
      "化学方程式配平与守恒",
      "原子守恒、系数与下标、括号原子计数、最简整数比及物质的量比；不含氧化还原电子配平、离子方程式和反应能否发生的判断",
      [],
      null,
      "balance",
      "chem-base",
    ],
    [
      "inheritance",
      "biology",
      "基因、配子与遗传概率",
      "基因与等位基因、基因型与表现型、分离定律、单基因完全显性杂交与条件概率；不含伴性遗传、连锁、多基因性状和基因表达机制",
      [],
      null,
      "inheritance",
      "bio-base",
    ],
  ].map(([id, subject, title, scope, prerequisites, topic, training, category]) => ({
    id,
    subject,
    title,
    scope,
    prerequisites,
    topic,
    training,
    category,
    version: 1,
    stage: "高中及必要前置基础",
  }));
  /* 按分类生成树结构：{ subjectId: [{ id, name, icon, nodes: [...] }] } */
  const getTree = () => {
    const tree = {};
    for (const [subjectId, cats] of Object.entries(categories)) {
      tree[subjectId] = cats.map(cat => ({
        ...cat,
        nodes: nodes.filter(n => n.category === cat.id),
      }));
    }
    return tree;
  };
  const get = (id) => nodes.find((n) => n.id === id);
  const href = (id, mistakeId) => {
    const n = get(id);
    if (!n) return null;
    const origin = mistakeId ? "&mistake=" + encodeURIComponent(mistakeId) : "";
    return n.training
      ? "training.html#module=" + encodeURIComponent(n.training) + origin
      : n.topic
        ? "index.html#topic=" + encodeURIComponent(n.topic) + origin
        : null;
  };
  root.Curriculum = { version: 3, subjects, nodes, categories, get, getTree, href, topicSubjects, nodeCategory };
})(typeof window === "undefined" ? globalThis : window);
